### PR TITLE
remove redundant tooltips

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # .

### CODE REVIEW

**Comment by dneukirchen** [comment]
Shouldnt we also remove 

https://github.com/joomla-projects/media-manager-improvement/blob/dev/plugins/filesystem/local/local.xml#L29

and 

https://github.com/joomla-projects/media-manager-improvement/blob/dev/plugins/filesystem/local/local.xml#L36

?

**Comment by laoneo** [comment]
Is this not a duplicate of #389?

**Comment by brianteeman** [comment]
@laoneo yes its a duplicate of that PR - sorry

@dneukirchen yes - i didnt look at that plugin

**Comment by brianteeman** [comment]
Closed in favour of 389

**Pull request closed without merging**
