### PR TITLE
Column layout for edit view

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #127 .

### Summary of Changes
A layout change to the edit view. Not sure what else I can do here as I can't edit the markup as easily as the browse page.

### CODE REVIEW

**Comment by laoneo** [comment]
I'm not sure if we should do three columns. If yes, then the plugins area should align them vertically like an accordion or not? When there are many plugins activated the tabs get stacked then?
Also some margins between the edit area and the preview would be nice to have.
image

**Comment by ciar4n** [comment]
Do we need the preview? The edit and preview pretty much display the same thing. Ideally I think plugin options and image should be visible without scroll.

How many plugins will there be?

**Comment by laoneo** [comment]
Actually there are three, but the list can grow when extension devs do start to create new ones, there is not a fixed amount.

**Comment by dneukirchen** [comment]
I think we can remove the "actual" preview column to get more space for editing. Nobody needs the image 2 times on the page.

**Comment by dneukirchen** [comment]
I had this layout in mind: 
bildschirmfoto 2017-05-19 um 19 32 35

**Comment by ciar4n** [comment]
Considering we go down to a single preview, is there any need for the preview title ('edit area', 'actual preview')? Personally I would say not as it is pretty self explanatory.

**Comment by ciar4n** [comment]
media-edit1

**Comment by dneukirchen** [comment]
Agree, no need for the title. 
Looks good. thank you @ciar4n  

@laoneo what do you think?

**Comment by ciar4n** [comment]
I have applied this to the crop plugin however don't merge as needs some changes

**Comment by laoneo** [comment]
For me it looks fine, cleane up and simple. I'm not sure if we can skip the editing area for the crop plugin. @dgt41 guess your input is needed here.

**Comment by dneukirchen** [comment]
We dont remove the "editing" area, we remove the "preview" area. Do you think we need it?

**Comment by laoneo** [comment]
Resize and rotate has only preview? Will that then become the editing area when they are activated?

**Comment by dgrammatiko** [comment]
> We dont remove the "editing" area, we remove the "preview" area. Do you think we need it?

If we're gonna go the no action button, then the 2 images is kinda expected, so the user understands whites happening in the window especially for crop. So personally I would add back the action button for crop

Other than that, of course I like the new layout...

**Comment by ciar4n** [comment]
Ready for testing

**Comment by laoneo** [comment]
For me it is ok.

Just a minor not (as usual):
I would put the controls on the left side. When I change the plugins or do a toolbar action like save, then I'm on the left side, but when I want to change something in the controls, then I need to go to the right side of the screen. It gets somehow nervous.

**Comment by dgrammatiko** [comment]
> I would put the controls on the left side. 

Right is the new left. What I mean is that in current (mobile) era the apps tend to have the most prominent actions on the right not on the left...

**Comment by laoneo** [comment]
Sounds as an argument :+1: . I still think the stuff needs to closer to each other, the following gif shows what I'm talking about.
webinstaller-3
 But if you guys are comfortable with it, then I'm fine merging it.

**Comment by dneukirchen** [comment]
I agree with allon. The mouseflow is not optimal in the current layout. I will merge it anyway and we will check the user-feedback from jab and ux-testing.

**Review by dneukirchen — APPROVED** [review]

**Comment by dneukirchen** [comment]
thank you sooo much @ciar4n 👍

**Pull request merged**
