### PR TITLE
Use / as directory separator

### PR DESCRIPTION
**Pull request by dneukirchen**
Pull Request for Issue #121  .

### Summary of Changes
Use / as directory separator

### CODE REVIEW

**Comment by laoneo** [comment]
Should the other functions not being adapted as well?

**Comment by N6REJ** [comment]
why are we calling a function that kills J!? LOL..
`		echo $this->rootPath.' '. $path;die;`
I'm really confused by this whole system of pathing... We've got very valid path tools already in J!

**Comment by TobsBobs** [comment]
I have copy the administrator/components/com_media/libraries/media/file/adapter/local.php from here and paste it in my installation. This don´t work on my windows pc. Media Manager is empty.

**Comment by dneukirchen** [comment]
@TobsBobs can you test it again. Should work now.

**Comment by N6REJ** [comment]
@test works as expected.  Win 10 x64 pro + ampps ( lamp )
pre:  

image


post: 
image

**Comment by TobsBobs** [comment]
unbenannt

@test works as expected. Win 10 x64 pro + xampp

**Comment by dneukirchen** [comment]
thanks @TobsBobs @N6REJ

**Comment by laoneo** [comment]
Great work. Can you guys also do a `composer install` and then `libraries/vendor/bin/phpunit tests/unit/suites/administrator/components/com_media/libraries/file/LocalAdapterTest.php`. Does it run trough on windows?

**Comment by TobsBobs** [comment]
When i came home, yes. 🍻

**Review by kasvith — APPROVED** [review]
This commit fixes the issue #121.
Also it closes the New Folder window after folder creation, it was a bug too.

I suggest to merge this PR

**Comment by kasvith** [comment]
Works perfectly, nice work @dneukirchen  
image

**Comment by TobsBobs** [comment]
here ist the log:


Setting environment for using XAMPP for Windows.
Tobi@TOBSBOBS c:\xampp
cd htdocs/media

Tobi@TOBSBOBS c:\xampp\htdocs\media
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 32 installs, 0 updates, 0 removals
  - Installing symfony/stopwatch (v3.2.4) Loading from cache
  - Installing symfony/process (v3.2.4) Loading from cache
  - Installing symfony/finder (v3.2.4) Loading from cache
  - Installing symfony/filesystem (v3.2.4) Loading from cache
  - Installing symfony/event-dispatcher (v3.2.4) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/debug (v3.2.4) Loading from cache
  - Installing symfony/console (v3.2.4) Loading from cache
  - Installing sebastian/diff (1.4.1) Loading from cache
  - Installing friendsofphp/php-cs-fixer (v1.13.1) Loading from cache
  - Installing pear/cache_lite (v1.8.0) Loading from cache
  - Installing webmozart/assert (1.2.0) Loading from cache
  - Installing phpdocumentor/reflection-common (1.0) Loading from cache
  - Installing phpdocumentor/type-resolver (0.2.1) Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.1) Loading from cache
  - Installing sebastian/version (1.0.6) Loading from cache
  - Installing sebastian/global-state (1.1.1) Loading from cache
  - Installing sebastian/recursion-context (1.0.5) Loading from cache
  - Installing sebastian/exporter (1.2.2) Loading from cache
  - Installing sebastian/environment (1.3.8) Loading from cache
  - Installing sebastian/comparator (1.2.4) Loading from cache
  - Installing phpunit/php-text-template (1.2.1) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8) Loading from cache
  - Installing phpunit/php-timer (1.0.9) Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2) Loading from cache
  - Installing phpunit/php-token-stream (1.4.11) Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4) Loading from cache
  - Installing phpspec/prophecy (v1.7.0) Loading from cache
  - Installing phpunit/phpunit (4.8.35) Loading from cache
  - Installing phpunit/dbunit (1.4.1) Loading from cache
  - Installing squizlabs/php_codesniffer (1.5.6) Loading from cache
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files

Tobi@TOBSBOBS c:\xampp\htdocs\media
libraries/vendor/bin/phpunit tests/unit/suites/administrator/components/com_media/libraries/file/LocalAdapterTest.php
Der Befehl "libraries" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Tobi@TOBSBOBS c:\xampp\htdocs\media

**Comment by N6REJ** [comment]
@laoneo thats the wrong path... E:\ampps\www\media-manager-improvement\tests\unit\suites\administrator\components\com_media\libraries\file\LocalTestAdapter.php is the correct one.
image

E:\ampps\php>composer -v
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.4.1 2017-03-10 09:29:45

**Comment by N6REJ** [comment]
if I do a composer update from nmm root it installs a LOT of files inside the J! folders

**Comment by dneukirchen** [comment]
we are green.
bildschirmfoto 2017-04-02 um 08 17 36

**Comment by laoneo** [comment]
Thanks David!!

**Comment by laoneo** [comment]
@N6REJ you need to do a composer install. It installs the dev packages like phpunit. If you run then composer install --no-dev, it reverts them.

**Comment by TobsBobs** [comment]
With "libraries/vendor/bin/phpunit" tests/unit/suites/administrator/components/com_media/libraries/file/LocalAdapterTest.php it works!

**Comment by N6REJ** [comment]
took me forever but I got 

> E:\ampps\www\media-manager-improvement>"libraries/vendor/bin/phpunit" tests/unit/suites/administrator/components/com_media/libraries/file/LocalAdapterTest.php
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

............

Time: 19.39 seconds, Memory: 14.00MB

OK (12 tests, 69 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done

User deprecation notices (15)

JFactory::getSession() is deprecated. Load the session from the dependency injection container or via JFactory::getApplication()->getSession(): 12x
    4x in LocalAdapterTest::testGetFiles
    4x in LocalAdapterTest::testGetFilteredFiles
    2x in LocalAdapterTest::testGetFile
    2x in LocalAdapterTest::testGetSingleFile

JFactory::getConfig() is deprecated. The configuration object should be read from the application: 2x
    1x in LocalAdapterTest::setUp
    1x in LocalAdapterTest::testGetFile

JFactory::createConfig() is deprecated. The configuration object should be read from the application: 1x
    1x in LocalAdapterTest::setUp


E:\ampps\www\media-manager-improvement>

**Pull request merged**
