### PR TITLE
Check if the path is properly formated

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #470.

Checks if the path is properly formated. You can test it by opening the url /administrator/index.php?option=com_media&format=json&task=api.files&url=true.

### CODE REVIEW

**Review by dneukirchen — COMMENTED** [review]
Suggestion: both methods in one line of code:

```
list($adapter, $path) = array_pad(explode(':',$this->input->getString('path')), 2, null);
```

**Comment by dneukirchen** [comment]
If you dont want to use array_pad, then the return of the getPath method should be `$parts[1]` instead of if `$parts[0];`.

**Comment by laoneo** [comment]
True, copy paste issue. Fixed to $parts[1]. Thanks.

**Comment by dneukirchen** [comment]
thx @laoneo

**Pull request merged**
