### PR TITLE
Action plugins improvements

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### CODE REVIEW

**Comment by laoneo** [comment]
Just if somebody is stumbling on this one, png images resize is working, but the new image doesn't get refreshed in the edit view.

**Comment by dgrammatiko** [comment]
Resize 
screen shot 2017-04-07 at 11 09 30

**Comment by ciar4n** [comment]
Would it be better to use input fields with up and down arrows rather than sliders? 

Sliders are a bit of a head wreck when you wish to set exact dimensions quickly.

**Comment by dgrammatiko** [comment]
@ciar4n this is still WIP, once we are happy with the codebase (javascript/php) you and the UX team could take over and do your thing. Also I just wanted to demo another approach, but anyhow, changing the slider to buttons or input or dropdown is very simple task...

**Comment by dgrammatiko** [comment]
And we have history:
screen shot 2017-04-07 at 15 18 48

**Comment by dgrammatiko** [comment]
Plugins client side code:
```js
		// Register the Events
		Joomla.MediaManager.Edit['nameOfThePlugin'] = {
			onActivate: function(mediaData) {
				// Initialize
			},
			onDeactivate: function() {
				// Destroy the instance
			}
		};
```

That's it!

**Comment by dgrammatiko** [comment]
Ok, I think I'm done here and now we have a solid API:

### METHODS
Activate/deactivate a plugin
```js
// Register the Events
Joomla.MediaManager.Edit['nameOfThePlugin'] = {
	Activate: function(mediaData) {
		// Initialize
	},
	Deactivate: function() {
		// Destroy the instance
	}
};
```

#### Getters:

Get the unmodified media file
```js
Joomla.MediaManager.Edit.original.contents
```
Get the current state media file
```js
Joomla.MediaManager.Edit.current.contents
```
Get the filename of the media file
```js
Joomla.MediaManager.Edit.original.filename
```
Get the extension of the media file
```js
Joomla.MediaManager.Edit.original.extension
```
#### Setters
Update the store
```js
Joomla.MediaManager.Edit.current.contents
```
Update the store:
```js
Joomla.MediaManager.Edit.current.contents = 'contents base64 encoded'
```
Create history entry:
```js
// Notify the app that a change has been made
window.dispatchEvent(new Event('mediaManager.history.point'));
```

**Comment by dgrammatiko** [comment]
Did the rotate plugin as well
screen shot 2017-04-08 at 17 42 15

**Pull request merged**
