### PR TITLE
Some toolbar icons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Adds some static icons to the toolbar. 

For now the intent is to use these to toggle a class on the 'media-browser' div. @dneukirchen .. your vue expertise would be needed here :)

media-icons

### CODE REVIEW

**Comment by dneukirchen** [comment]
thx @ciar4n

**Comment by laoneo** [comment]
Is this ready to merge then?

**Comment by ciar4n** [comment]
Yes it can be merged

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
