### PR TITLE
Check if the mime_content_type exists

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for comment in main repo https://github.com/joomla/joomla-cms/issues/16586#issuecomment-307553504.

### Summary of Changes
Adds a check if the function `mime_content_type` exists.

### CODE REVIEW

**Comment by brianteeman** [comment]
this will only partially address the issue. as this is now a requirement for joomla we need to add it to the preinstallation checks, system info reports etc etc

**Comment by laoneo** [comment]
It is not a requirement, more of a nice to have.

**Comment by brianteeman** [comment]
it is a requirement as its completely broken without it

**Comment by laoneo** [comment]
What is broken without it? Just the mime type is not displayed.

**Comment by zero-24** [comment]
What about this method as it has some more fallbacks: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/media.php#L59 ?

Need to be declared as public first but can be done.

**Comment by laoneo** [comment]
@zero-24 good catch, will change it to that function then.

**Comment by laoneo** [comment]
Updated to the mediahelper function

**Comment by dneukirchen** [comment]
Thx @laoneo

**Review by dneukirchen — APPROVED** [review]

**Pull request merged**
