### PR TITLE
Move modal title to header

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #450 & #449 .

### Summary of Changes
Moves the modal title to the header inline with the close button

image

### CODE REVIEW

**Comment by brianteeman** [comment]
Out of interest what about keeping the text in white on the black background but in the new location?

**Comment by laoneo** [comment]
Somehow the name area with the close button do look for me not clear. Perhaps we should try out the GMail way:
image

**Comment by ciar4n** [comment]
So with the black background...

image

**Comment by ciar4n** [comment]
And with Allons suggestion...

image

**Comment by brianteeman** [comment]
I like the allon version with the icon and text together

**Comment by ciar4n** [comment]
With you on that. Considering there is currently only a title and close and think best keep them together.

Should I link just the icon or the icon and filename to close the modal?

**Comment by ciar4n** [comment]
Ideally I think if anywhere outside the image is clicked the modal should close.

**Comment by laoneo** [comment]
Just tested it with GMail. If you click on the name you can select it, nothing happens. If you click on the black area, it closes. If you hover over the back button, then it changes the background to grey of the arrow.

**Comment by ciar4n** [comment]
K.. let's go with that.

**Comment by ciar4n** [comment]
Latest commit...

- Move close/back next to title
- Changed icon to an arrow
- Anywhere outside the image and title now closes the modal
- Grey background on hover of the back icon as displayed in the screenshot

image

**Comment by laoneo** [comment]
Looks nice to me and worked fine. @brianteeman ok for you too? Would love to merge it.

**Comment by brianteeman** [comment]
Go for it. might need an RTL tweak but that can be done later in a full rtl review

**Comment by laoneo** [comment]
Gj!

**Pull request merged**
