### PR TITLE
[WIP] Make the cropper plugin properly work

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### CODE REVIEW

**Comment by laoneo** [comment]
Did you test the resize, crop and rotate plugins? Are they still working?

**Review by dneukirchen — COMMENTED** [review]
I dont really like putting component specific deps in the media vendors folder, but im ok with it in this case.

Perhaps it would be a good idea to namespace it with Joomla.Event? 

Would be also nice to wrap the specific implementation (eventbausjs) in a joomla wrapper, so that we can exchange it when needed.  In that wrapper we could also simplify the naming:

* `fire` instead of `dispatch`
* `listen` instead of `addEventListener`

So it comes down to `Joomla.Event.fire(event, payload)` and `Joomla.Event.listen(event, callback)`.

**Comment by dneukirchen** [comment]
#130

**Comment by laoneo** [comment]
@dgt41 what do you think to split that pr into multiple ones? It is hard to review at the moment as too many things are done here at the same time.

**Comment by dneukirchen** [comment]
@dgt41 should we close this one in favor of #152 and upcoming prs?

**Pull request closed without merging**
