### PR TITLE
Feature/improve file upload with duplicate file name

### PR DESCRIPTION
**Pull request by dneukirchen**
Pull Request for Issue #184 .

bildschirmfoto 2017-09-27 um 16 52 43

When the file already exists, the user has to answer if he wants to override it. 

bildschirmfoto 2017-09-27 um 16 53 12

@laoneo we need to implement that on server side:
when we send a "override=true" param to server along with an upload request, the server should override the existing file. If override=true is not present in request params and the file already exists, the server should return a 409 error response and not override or modify the file. The rest will be done in the client..

### CODE REVIEW

**Comment by dneukirchen** [comment]
If override=true is not present in request params and the file already exists, the server should return a 409 error response and not override or modify the file. The rest will be done in the client.

**Comment by kasvith** [comment]
@dneukirchen shouldn't it be override=1 ?

**Comment by dneukirchen** [comment]
only if we use getBool() on server side, which we dont.

**Comment by kasvith** [comment]
gj @dneukirchen

**Pull request merged**
