### PR TITLE
Check the folder name the same way as with files

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #93.

### Summary of Changes
Reads the name from the input allowing more characters. The name is sanitized the same way as with file names.

### CODE REVIEW

**Review by dneukirchen — CHANGES_REQUESTED** [review]
When i create a new directory with whitespaces in the directory name, im getting a 404 not found error response. The directory is created, but i have to reload the page to see it.

Whitespaces are replaced by underscores not by dashes.

**Comment by laoneo** [comment]
Fixed the 403 error in the last commit.

> Whitespaces are replaced by underscores not by dashes.

That's the [behavior](https://github.com/joomla-projects/media-manager-improvement/blob/milestone1/administrator/components/com_media/models/api.php#L191) from the old media manager to replace the non-alphanumeric characters with an _.

**Review by dneukirchen — APPROVED** [review]
Looks good now. Let UX decide on the _ vs - thing.
Can you inform UX about this @laoneo ?

**Comment by laoneo** [comment]
Will do on the meeting today.

**Pull request merged**
