### PR TITLE
Image action icons for grid

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Add some icons on hover of images in grid. Edit icon linked to edit view.

media-grid-icons

### CODE REVIEW

**Comment by laoneo** [comment]
Nice one. Would it be possible to show them also when clicking on a file? Like that it would also work on touch devices.

**Comment by ciar4n** [comment]
For now it is simply..

media-check

I'll come up with something better.

For mobile I was thinking to always display the icons but with out the dark background. Something like...

media-mobile-icons

**Comment by laoneo** [comment]
Looks nice, thanks.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
