### PR TITLE
Adapt the crop ratio CSS selector

### PR DESCRIPTION
**Pull request by laoneo**
As the CSS selector got removed in #498. This pr adapts the styling.

### Before
image

### After
image

### CODE REVIEW

**Comment by schnuti** [comment]
Also with this you can get funny results when the column get too narrow. I hope "floating" buttons can fix it.  
not-very-responsive

**Comment by brianteeman** [comment]
Aspect ratio are usually written 4:3 not 4/3
I would change 2/3 to 3/2 so that all the ratios are in the same orientation
screenshotr10-56-32

screenshot from https://calculateaspectratio.com/

**Comment by laoneo** [comment]
@brianteeman can you open a new issue for that, or even a new pr? Thanks.

**Comment by brianteeman** [comment]
@laoneo ok

**Comment by schnuti** [comment]
Do not yet merge this until cleared if the radio buttons remain. The old class might be needed for other buttons. I'm adding a PR for an alternative now.

**Comment by laoneo** [comment]
Removed the button dependent code as it is not needed anymore because of the drop down from #503.

**Pull request merged**
