### PR TITLE
Add ie11 support

### PR DESCRIPTION
**Pull request by dneukirchen**
Pull Request for Issue #247

### CODE REVIEW

**Comment by Bakual** [comment]
It does improve it in that I now see the items, but there are still some issues:
* Console error on loading, without doing anything yet:
image

* Icons positioning is off:
image

* Clicking any element in the main area gives a console error and nothing happens otherwise:
image

There may be others, I stopped at this point :)

**Comment by dneukirchen** [comment]
Thx for testing. Lets try to not mix too many things into the issue.

* The first issue seems not related to media manager (looks like menu code) 
* Styling Icon may be a task for @ciar4n
* I will create a fix for the 3rd isssue.

**Comment by Bakual** [comment]
1. True, didn't check closer which JS file it was. Will verify later and open a new issue in core if I find out more
2. Do you want me to open a new issue for that styling?
3. Great.

**Comment by laoneo** [comment]
@dneukirchen can you fix the merge conflict, then I will merge it as the other issue will be handled separate?

**Comment by Bakual** [comment]
Opened a new issue for 1: https://github.com/joomla/joomla-cms/issues/16688

For the icon one, we first have to merge this one so it can actually be seen :smile:

**Comment by dneukirchen** [comment]
@Bakual fixed the 3rd issues, can you check again? Thx.
merge conflict resolved.

**Comment by Bakual** [comment]
That fixed it. Also the icons are now positioned correctly.

**Comment by dneukirchen** [comment]
Thx @Bakual

**Pull request merged**
