### PR TITLE
Updated UnitTests

### PR DESCRIPTION
**Pull request by kasvith**
Contains Unit Test Cases updates for new API features

### CODE REVIEW

**Comment by kasvith** [comment]
This pr is not dependent

**Comment by laoneo** [comment]
Can you add the following change to the branch, so drone will exclude all vendor dirs:

```
Index: build/phpcs/Joomla/ruleset.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- build/phpcs/Joomla/ruleset.xml	(revision 61dc51835473eac9827053964b59c885df8655b6)
+++ build/phpcs/Joomla/ruleset.xml	(revision )
@@ -17,7 +17,7 @@
 	<exclude-pattern type="relative">libraries/phputf8/*</exclude-pattern>
 	<exclude-pattern type="relative">libraries/simplepie/*</exclude-pattern>
 	<exclude-pattern type="relative">libraries/phpass/*</exclude-pattern>
-	<exclude-pattern type="relative">libraries/vendor/*</exclude-pattern>
+	<exclude-pattern type="relative">*/vendor/*</exclude-pattern>
 	<!-- Exclude the restore_finalisation until we can deal with nested class definitions -->
 	<exclude-pattern type="relative">administrator/components/com_joomlaupdate/restore_finalisation.php</exclude-pattern>
 	<exclude-pattern type="relative">administrator/components/com_joomlaupdate/restore.php</exclude-pattern>
```

Its a patch, which you should be able to apply directly from the clipboard.

**Comment by kasvith** [comment]
Sure, i will

**Comment by kasvith** [comment]
@laoneo drone fail because of some cs errors in dropbox plugin, the next #286  fix them so good to merge

**Comment by laoneo** [comment]
Drone still fails.

**Comment by kasvith** [comment]
this PR is merged locally to #286 to ensure both drone and travis work
Unfortunately because of a test case in upstream *javascript* drone will fail.

**Comment by kasvith** [comment]
Since this is merged to #286 it is safe to close this

**Comment by kasvith** [comment]
closing PR since it is locally merged to #286

**Pull request closed without merging**
