### PR TITLE
[ Fix ] Actions on directories does not close itself

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue #525

### Summary of Changes
Make show action false <code>@mouseleave="showActions = false"</code>

### Testing Instructions

    1. Open NMM
    2. Click the button on a directory while hovering
    3. Click another file or directory's action button too

### Expected result
After clicking another directory the actions should be disappears.

### Actual result
Opened action lists are still available

### CODE REVIEW

**Comment by kasvith** [comment]
Seems working fine for me, tested locally

**Comment by dneukirchen** [comment]
thx @Anu1601CS 

Can you apply the same fix to file and video component?

**Comment by dneukirchen** [comment]
https://github.com/joomla-projects/media-manager-improvement/blob/dev/administrator/components/com_media/resources/scripts/components/browser/items/video.vue#L2

**Comment by dneukirchen** [comment]
https://github.com/joomla-projects/media-manager-improvement/blob/dev/administrator/components/com_media/resources/scripts/components/browser/items/file.vue#L2

**Comment by anuragteapot** [comment]
@dneukirchen Done!

**Comment by kasvith** [comment]
Thanks @Anu1601CS

**Comment by anuragteapot** [comment]
@kasvith You're welcome

**Pull request merged**
