### PR TITLE
fix typo in css

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21023
obvious typo - reported by  @Hackwar

### CODE REVIEW

**Comment by laoneo** [comment]
You need to run `npm run build` in the folder /administrator/components/com_media to also rebuild the css file.

**Comment by brianteeman** [comment]
someone else can do it then - I am not installing npm etc for such a tiny pr

**Comment by brianteeman** [comment]
especially as the mediamanager.css and min.css are both minified - so there is obviously a bigger issue

**Comment by laoneo** [comment]
mediamanager.css is probably a leftover as we ship only the min file since #547. So you want to close it then and reopen the other issue?

**Comment by laoneo** [comment]
A vue file was still referencing the old class. It got it fixed in together with your patch 56a51ad6ccb8755503e0c4e8939b8a558db9dd02. Thanks for your help!

**Pull request closed without merging**
