### PR TITLE
Suggestion: move checkall to upper left

### PR DESCRIPTION
**Pull request by dneukirchen**
What do you think about moving the checkAll checkbox in the upper left corner?

Before:
bildschirmfoto 2017-09-27 um 20 45 49

After: 
bildschirmfoto 2017-09-27 um 20 44 59

### CODE REVIEW

**Review by kasvith — COMMENTED** [review]
I would like to see it on toolbar

**Comment by ciar4n** [comment]
This works for me.

The only issue is it might be associated with the breadcrumbs. Top left is the same location as android however they hide the breadcrumbs when one or more items are selected and replace it with a select all checkbox followed by the number of items selected. This resolves the breadcrumbs association issue.

**Review by ciar4n — APPROVED** [review]

**Comment by rgmears** [comment]
This is a variation on what @dneukirchen has presented. I admit to changing the colour scheme a little, but the drift here is to make the work area as large as possible:
j4-media-manager-1

**Comment by dneukirchen** [comment]
thx @rgmears i like the idea, but unfortunately we cant change the joomla admin toolbar. This is something the joomla 4 template team is currently working on.

**Comment by laoneo** [comment]
I'm here on the same page as @dneukirchen, this should be discussed with the template team and then we will adapt to their standard. But I think it is worth to rethink the toolbar setup as what we have now is the same since ages.

For now I would like to keep focus on the issue the pr tries to solve, to move the select all checkbox to the left side.

**Comment by rgmears** [comment]
I'm curious @dneukirchen and @laoneo why the breadcrumbs are needed at all. It's quite obvious where the user is in terms of folder hierarchy. If the breadcrumbs were omitted and the select all checkbox returned to its original location the images pane could be even taller (almost the full height of the screen).
j4-media-manager-4

**Comment by brianteeman** [comment]
They are essential for accessibility!

**Comment by rgmears** [comment]
Why?

**Comment by brianteeman** [comment]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-location.html

**Comment by rgmears** [comment]
Seems redundant to me @brianteeman. 
There is no breadcrumb trail on any other screen in the backend.

**Comment by brianteeman** [comment]
No other screen in the admin allows navigation in this way

**Comment by rgmears** [comment]
Well navigation this way -- breadcrumbs -- only allows for going backwards and is IMO useless. Just a waste of screen space.

**Comment by brianteeman** [comment]
You dont understand the accessibility - it is not about navigation anywhere - it is about knowing where you are

**Comment by brianteeman** [comment]
It is only useless to you because you do not face any barriers when you use the internet

**Comment by rgmears** [comment]
Seems pretty obvious to me where I am in the folder hierarchy.
j4-media-manager-detail-1
Although I don't understand what you mean by facing barriers. What sort of barriers?

**Comment by brianteeman** [comment]
1. you can see
2. you have cognitive skills that allow you to navigate complex paths and understand them

**Comment by rgmears** [comment]
Why would blind people be working with images?
And, if the breadcrumbs are only about knowing where you are, why are they linked?
Do people lacking "cognitive skills" add content to Joomla! websites?

**Comment by brianteeman** [comment]
OK I am not even going to comment on your totally ignorant and offensive comments. I hope that you will spend a few moments to think and reflect about what you just said.

**Comment by rgmears** [comment]
I think it would be more appropriate for you to answer my questions.

**Comment by brianteeman** [comment]
Sorry but I dont respond to ignorant offensive comments

**Comment by mbabker** [comment]
> Do people lacking "cognitive skills" add content to Joomla! websites?

Yes.  People with physical and mental disabilities (as in having impaired "cognitive skills") are commonly managing websites (not just Joomla installations).

**Comment by rgmears** [comment]
> People with physical and mental disabilities (as in having impaired "cognitive skills") are commonly managing websites

OK. But, how do the breadcrumbs help such people?

**Comment by mbabker** [comment]
A breadcrumb tree more capably communicates the current navigation path than trying to determine it from the menu structure applicable to that area (in the media manager that'd be the folder tree in the sidebar, in your site frontend that's usually your main menu tree).  It also allows users to easily traverse up the site navigation without having to find the content in the menu tree.

**Comment by rgmears** [comment]
I notice (now) that Windows Explorer has an address bar which emulates breadcrumbs. I've never used it. And Nemo (files browser on Linux) has a top bar which performs the same function as breadcrumbs, which I glance at occasionally. Still, to go to another folder one has to scroll the folder tree in sidebars on both Windows and Linux, unless, of course, one is just going back a folder or two.

It still seems superfluous to me to have breadcrumbs on the Media Screen.

**Comment by dneukirchen** [comment]
Agree with @mbabker and @brianteeman. We should keep the breadcrumb. For many users it is still a very important and easy to use navigation and orientation element. 

@rgmears i really appreciate your interest and efford and we are always open minded for new ideas and suggestions. 

For this PR: lets get back to the topic. Dont hesitate to open separate issues or send a pull request if you have any further feedback, suggestions or issues with/for the new media manager.

**Comment by brianteeman** [comment]
Let me be clear. breadcrumbs are NOT about navigation. They are about telling you where you are. Breadcrumbs do not have to be clickable, although typically they are, that is just a bonus.

**Comment by rgmears** [comment]
With the folder tree being so prominent the breadcrumbs, in this case, are a distraction.

**Comment by dneukirchen** [comment]
guys ;-) this PR is not about what a breadcrumb is (not) or should be... 

https://github.com/joomla-projects/media-manager-improvement/issues/new if you really want to discuss that any further...

**Comment by rgmears** [comment]
Done: https://github.com/joomla-projects/media-manager-improvement/issues/424

**Comment by brianteeman** [comment]
I tend to agree with @ciar4n 
> The only issue is it might be associated with the breadcrumbs.

**Comment by laoneo** [comment]
As far as I got the impression is that most here do agree that it would make sense to move the select all action to the left side. So I suggest that when we get rid of the >, that it doesn't look like it belongs to the breadcrumbs, we can merge it.

**Comment by dneukirchen** [comment]
made adjustements

bildschirmfoto 2017-09-29 um 18 49 43

**Comment by laoneo** [comment]
Thanks

**Comment by rgmears** [comment]
Just out of curiosity, what am I as a user likely to do after I've selected ALL of the images?

**Comment by dneukirchen** [comment]
delete

**Comment by rgmears** [comment]
And where on the page do I do that?

**Comment by dneukirchen** [comment]
There is a red button in the toolbar.

In the future i can think of other batch operations. Something like download as zip or moving multiple items between folders.

**Comment by rgmears** [comment]
What are the **-** and **+** buttons for?

**Comment by dneukirchen** [comment]
they in/decrease the grid item size. 
probably we need to change those buttons to somthing like http://fontawesome.io/icon/search-plus/

**Comment by rgmears** [comment]
OK. Thanks.

**Comment by rgmears** [comment]
@brianteeman 
Regarding the breadcrumbs, I noticed that it is built into the code for the Media Manager page. If it were placed as a module (as other admin template elements are) then it would be the user's choice whether to display them or not. Of course, though, that would mean moving the checkall back to where it was originally.

**Comment by rgmears** [comment]
I think it would be better to move the check-all button back to where it was. Then it is beside the "-" button which is the next action in the sequence. One would check (select) all then delete from what has been said here.

**Pull request merged**
