### PR TITLE
Add aria-label to toolbar and grid item icons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
i will check this after lunch

**Comment by brianteeman** [comment]
First observation is that the language strings should be alpha sorted. I know it doesnt make sense but that is the standard

**Comment by brianteeman** [comment]
You missed one 
https://github.com/joomla-projects/media-manager-improvement/blob/bd25b3b450950bc9d0fa2250e11bcd5b3a7804d4/administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue#L26

**Comment by ciar4n** [comment]
Thank you. Language alpha sorted and aria-label added to info icon

**Comment by brianteeman** [comment]
Thanks - looks good to me and a great **start** to making this component accessible.

**Review by dneukirchen — APPROVED** [review]

**Comment by dneukirchen** [comment]
thx!

**Pull request merged**
