### PR TITLE
Check if the path is within the root folder

### PR DESCRIPTION
**Pull request by laoneo**
The API does not support relative paths to work on.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
after applying this patch only on [4.0Alpha]  I get 

```json
{
error: true,
code: 0,
message: "Class 'Joomla\Plugin\Filesystem\Local\Adapter\InvalidPathException' not found"
}
```

**Comment by wilsonge** [comment]
I don't have that error :( are you sure the patch applied correctly?

I do get however an untranslated string COM_MEDIA_CREATE_NEW_FOLDER_ERROR shown as an alert

**Comment by PhilETaylor** [comment]
I should have said I get that error message when trying to fake url paths after applying the patch

screen shot 2017-11-19 at 08 54 33

**Comment by laoneo** [comment]
Just tested it and I can't reproduce the error. The exception class is loaded in two files and both have the proper use statement.

**Comment by laoneo** [comment]
@PhilETaylor could you test it with the latest commit, is it working now? Would like to get that pr in as I got the ok from JSST at JWC17.

**Comment by PhilETaylor** [comment]
The patch https://patch-diff.githubusercontent.com/raw/joomla-projects/media-manager-improvement/pull/467.patch is not cleaning applying to the 4.0-dev branch :(

**Comment by laoneo** [comment]
Let me sync 4.0-dev

**Comment by laoneo** [comment]
Now we are in sync with 4.0

**Comment by PhilETaylor** [comment]
Still not patching :(

**Comment by PhilETaylor** [comment]
```
~/Sites/joomla-cms(4.0-dev ✗) patch -p0 < 467.patch
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 760a45eca66b79f2e656f4f2503d41986208814c Mon Sep 17 00:00:00 2001
|From: Allon Moritz <allon.moritz@digital-peak.com>
|Date: Sat, 18 Nov 2017 16:52:47 +0100
|Subject: [PATCH] Check if the path is within the root folder
|
|---
| .../com_media/Controller/ApiController.php         |  5 ++
| plugins/filesystem/local/Adapter/LocalAdapter.php  | 84 +++++++++++++++-------
| .../plugins/filesystem/local/LocalAdapterTest.php  | 63 ++++++++++++++++
| 3 files changed, 126 insertions(+), 26 deletions(-)
|
|diff --git a/administrator/components/com_media/Controller/ApiController.php b/administrator/components/com_media/Controller/ApiController.php
|index 13a3d90c5e..77836bf30e 100644
|--- a/administrator/components/com_media/Controller/ApiController.php
|+++ b/administrator/components/com_media/Controller/ApiController.php
--------------------------
File to patch: administrator/components/com_media/Controller/ApiController.php
patching file administrator/components/com_media/Controller/ApiController.php
can't find file to patch at input line 39
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/plugins/filesystem/local/Adapter/LocalAdapter.php b/plugins/filesystem/local/Adapter/LocalAdapter.php
|index b704ebe5e1..3f42fddc81 100644
|--- a/plugins/filesystem/local/Adapter/LocalAdapter.php
|+++ b/plugins/filesystem/local/Adapter/LocalAdapter.php
--------------------------
File to patch: plugins/filesystem/local/Adapter/LocalAdapter.php
patching file plugins/filesystem/local/Adapter/LocalAdapter.php
Hunk #1 FAILED at 11.
Hunk #2 succeeded at 89 (offset -2 lines).
Hunk #3 succeeded at 126 (offset -2 lines).
Hunk #4 FAILED at 178.
Hunk #5 FAILED at 204.
Hunk #6 FAILED at 227.
Hunk #7 succeeded at 234 (offset -20 lines).
Hunk #8 succeeded at 325 (offset -21 lines).
Hunk #9 FAILED at 375.
Hunk #10 FAILED at 485.
Hunk #11 succeeded at 609 (offset -44 lines).
Hunk #12 FAILED at 717.
Hunk #13 FAILED at 725.
Hunk #14 succeeded at 682 with fuzz 2 (offset -130 lines).
8 out of 14 hunks FAILED -- saving rejects to file plugins/filesystem/local/Adapter/LocalAdapter.php.rej
can't find file to patch at input line 250
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php b/tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php
|index 1a49fccccc..7fa89934be 100644
|--- a/tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php
|+++ b/tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php
--------------------------
File to patch: tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php
patching file tests/unit/suites/plugins/filesystem/local/LocalAdapterTest.php
Hunk #1 succeeded at 115 (offset -6 lines).
Hunk #2 succeeded at 229 (offset -6 lines).
Hunk #3 succeeded at 262 with fuzz 1 (offset -26 lines).
Hunk #4 succeeded at 298 with fuzz 1 (offset -49 lines).
```

**Comment by laoneo** [comment]
Strange, probably we did already too many changes in this repo in comparison to the 4.0-dev branch. Can you download and test it on a fresh install from the branch https://github.com/joomla-projects/media-manager-improvement/archive/fix/detect/invalid/path.zip

**Comment by PhilETaylor** [comment]
I would prefer to see a mergeable PR, as I dont know the state of `path.zip` contents

Using the code from path.zip I get a `400 Bad Request` on my faked urls with content

screen shot 2017-11-23 at 10 09 53

**Comment by laoneo** [comment]
This is what should come up.

**Comment by PhilETaylor** [comment]
you could fix this one too:

screen shot 2017-11-23 at 10 13 58

**Comment by laoneo** [comment]
It should return the contents of the current directory or not? At least thats what I get and what I see in your screenshot.

**Comment by dneukirchen** [comment]
thx

**Pull request merged**
