### PR TITLE
Add reset option for aspect ratio in crop plugin

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #490.

### Summary of Changes
Adds a reset button for the aspect ratio in the crop plugin.

image

### CODE REVIEW

**Comment by brianteeman** [comment]
From the image thats just a radio button option and not a reset button. It should be a button. My 2c

**Comment by schnuti** [comment]
Tested and it works!
@brianteeman It works as a Reset as long as you do not change to e.g. the resize view. Width and height go back to the original **in the crop view**.  You do a complete Reset with the button in the toolbar. This is ok for me.

@laoneo You were right. It was two issues. I'll add an issue for the "not checked" radio buttons so issue 490 can be closed.

**Comment by brianteeman** [comment]
it might work but its still not a button as per the title

**Comment by laoneo** [comment]
Changed the title.

**Comment by dgrammatiko** [comment]
For the other issue let’s add a first option: original aspect ratio which should be selected by default

**Comment by schnuti** [comment]
@dgt41 You mean yet another option I suppose. You still have to have an option where you can set width/height/pos-x/pos-y without any aspect ratio restrictions.

**Comment by ciar4n** [comment]
@brianteeman For these to appear as a button group we wait for https://github.com/joomla/joomla-cms/pull/19326 to be merged.

**Pull request merged**
