### PR TITLE
Disable form submission if the form is invalid

### PR DESCRIPTION
**Pull request by dneukirchen**
### Summary of Changes

Disable the "save" button until the create-folder-form is valid.

### CODE REVIEW

**Comment by kasvith** [comment]
A good idea we can stop showing an error each time

**Review by kasvith — APPROVED** [review]
This is a good mechanism to prevent user from trying to create folders with empty names

**Review by kasvith — APPROVED** [review]
Good to merge ASAP

**Comment by laoneo** [comment]
Drone is failing, because of the novalidate attribute, can you have a look please.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
