### PR TITLE
Feature/multi adapter

### PR DESCRIPTION
**Pull request by dneukirchen**
Simple implemtation of multi adapter support in client.
I dropped my first idea to have nested vuex modules for each disk, but i will keep the changes in the `multi-adapter-support` branch. Perhaps we have to switch to that method later

Please note: because of the path changes the image preview and some file operations do not work atm.

### CODE REVIEW

**Comment by laoneo** [comment]
The images are not displayed in the list.

Additionally the tree looks a bit strange with this line crossing the icons
image

**Comment by laoneo** [comment]
The database install/update script needs to be updated, setting the title information, because when the local plugin doesn't have a title saved in the params, then it will not displayed in the tree.

**Comment by dneukirchen** [comment]
> The images are not displayed in the list.

Yes. This is because of the path changes. I could have removed it in the client, but for remote providers it will not work (when the resources are not public). So we have to make some decisions here before i will implement it.

> Additionally the tree looks a bit strange with this line crossing the icons

Jups. WIP. => we need styling before merging gsoc to ms1

> The database install/update script needs to be updated, setting the title information, because when the local plugin doesn't have a title saved in the params, then it will not displayed in the tree.

Yes, but imo this is not related to this PR as it focusses on the client. I already told @kasvith that the defaults are missing.

**Comment by laoneo** [comment]
Merged it so we can move on. Thanks!

**Comment by kasvith** [comment]
@dneukirchen it has default values in local.xml

**Comment by dneukirchen** [comment]
Yes, but 

> The database install/update script needs to be updated, setting the title information, because when the local plugin doesn't have a title saved in the params, then it will not displayed in the tree.

**Pull request merged**
