### PR TITLE
Fix file get renamed to an existing file

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue #527

### Summary of Changes
Changes in <code>ApiController</code>
Initially, set <code>$force</code> false.
To not force to overwrite

### Testing Instructions

Rename a file to an existing file or a folder to an existing folder

### Expected result

Rename should not be possible

### Actual result
Rename is possible.

### CODE REVIEW

**Comment by anuragteapot** [comment]
@dneukirchen Can you please review ?

**Comment by kasvith** [comment]
Ok this seems fine. It can be merged.
For some weird reason i ve forced it there by default. 

We need some option to whether force or not for move and copy.
Even though rename uses **move** we need to distinguish it with the others as for any reason rename should not be forced. Others can be forced on request in my opinion.

**Review by kasvith — APPROVED** [review]

**Comment by kasvith** [comment]
But i would wait until system tests are back online before merging it

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
