### PR TITLE
Mmfixes

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue # .

### CODE REVIEW

**Comment by laoneo** [comment]
Can you rebase your branch? Guess something screwed up. Just merged the 4.0-dev branch into milestone1.

**Comment by zero-24** [comment]
It is completly broken now.. I need to find time to do this again..

**Comment by zero-24** [comment]
@laoneo looks like you could fixed the branch now?

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
