### PR TITLE
Add the media file

### PR DESCRIPTION
**Pull request by laoneo**
The media file helper class

### CODE REVIEW

**Comment by zero-24** [comment]
Can we add a file doc block at the top?

**Comment by jissereitsma** [comment]
We can have docblocks later. There is still too much moving with this project to say we need to polish things. Things can be polished when the final code is in sight, I would say.

**Comment by zero-24** [comment]
Ok just ping me if you at that state. I hope i can find time than to help on that :)

**Comment by jissereitsma** [comment]
Thanks. There will be so much code moved and removed, that adding those blocks now would be a waste of time. But many thanks for the offer! We'll be in touch!

**Pull request merged**
