### PR TITLE
Allow spaces for file names on upload

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #260.

### Summary of Changes
Removes the code in the local adapter which strips out any none alpha numerich character. This is a follow up pr of #446.

### Testing Instructions
Upload a file with spaces.

### Expected result
Spaces do remain.

### Actual result
Spaces get stripped out.

### CODE REVIEW

**Comment by schnuti** [comment]
This PR resolves what it is supposed to. It does not what the title says but reverts to the use of an old method. Allowing _,- and blanks.

Über-größen_ länge.jpg becomes ber-gren_ lnge.jpg

I have some new general comments on #260

**Comment by schnuti** [comment]
Is it possible to override one specific method in LocalAdapter.php keeping the rest?
e.g. =>getSafeName($name)

**Comment by laoneo** [comment]
Can you try again. The problem was that basename stripps out certain characters like the upper case Ü characters but accepts the lower case one.

**Comment by schnuti** [comment]
Same result
Why shouldn't it? The characters get stripped at line 734

// Make the filename safe
   $name = \JFile::makeSafe($name);

If I comment out that line the AJAX response is
Message: COM_MEDIA_ERROR_UNABLE_TO_UPLOAD_FILE
Error:
0: File name must only contain alphanumeric characters and no spaces.

**Comment by laoneo** [comment]
Ok, reverted to code to just fix to allow spaces and changed the title accordingly. Should be fine now. Will open another pr for the rest.

**Comment by laoneo** [comment]
Lets discuss the umlaut issue in the pr #463.

**Comment by schnuti** [comment]
To be more precise. It's not a fix for spaces. It's a fix for the missing dashes mentioned in 260.
Allowed is now _ (underscore), - (dash) and ' ' (space, blank, whitespace) beside numbers and "english" characters.
Never mind, it's ok as is for now.

**Pull request merged**
