### PR TITLE
Feature/Login support in Dropbox

### PR DESCRIPTION
**Pull request by kasvith**
### Summary of Changes
- Updated Dropbox plugin to use OAuthCallback handler integrated with Joomla 4.x
- Dropbox will fetch your name automatically
- Unit tests are updated

### Testing Instructions
- Go to https://www.dropbox.com/developers and Login
- Go to **MyApps** and create a new app with **Full Dropbox Access**
- Go to settings of your App
- Scroll to **redirect_uri** and set it to **[host-name]/administrator/index.php?option=com_media&task=plugin.oauthcallback&plugin=dropbox**

Please replace [host-name] with your host.

- Go to Joomla backend
- Go to plugin settings of dropbox
- Copy **Client ID** , **Client Secret** from your Dropbox App Settings page and paste them in respective fields
- **Save your changes**
- Click the **Get Access Token** button
image
- If everything is correct you will be redirected to **Dropbox** , click **Allow Access** to proceed.
image

- Now you will be redirected to Media Manager with a message saying it was success
image

- It will rename your drive with the name of account by default. Well you can change that

### Expected result
- Working dropbox adapter with login

### Actual result
- It works

### CODE REVIEW

**Comment by laoneo** [comment]
Why do you use two different dropbox libraries?

**Comment by kasvith** [comment]
1st one does not have authentication capability, its used by flysystem 

The new one has authentication capability which i needed to use

**Comment by laoneo** [comment]
Should we then not just use the second one, or does it not have all the features we need? I feel a bit hesitant to merge it with two sdk's.

**Comment by kasvith** [comment]
It does not have all the features, i use flysystem in the plugin it require 1st library

**Comment by laoneo** [comment]
I tested it and I get a 400 error where it always tried to create a redirect uri with localhost.

**Comment by kasvith** [comment]
Can you post a screenshot please

**Comment by laoneo** [comment]
image

**Comment by kasvith** [comment]
Oops there is some hardcoding, i will fix that

**Comment by kasvith** [comment]
@laoneo drone fails because of upstream

**Comment by kasvith** [comment]
merged #287 locally

**Comment by kasvith** [comment]
#287 was locally merged to this and pr was closed

**Comment by kasvith** [comment]
@laoneo thanks for the effort

**Pull request merged**
