### PR TITLE
Add flip functionality to the image crop view

### PR DESCRIPTION
**Pull request by schnuti**
Pull Request for Issue #507 

_Description from the issue_
With only a few lines the flip functionality can be added to the image crop view. This is often used in particular if the base is an analogue image negative or diapositive where up and down/left and right easily gets incorrect. 
Flip is included in the existing rotate events. A click on 0 degrees flips the image without rotation.
See gif animation. I'll add a PR later.

flip-flop

### CODE REVIEW

**Comment by schnuti** [comment]
It would be nice to have buttons for the check boxes like the radio buttons.
There was a javascript for this in J3 but I think this has bin removed with no replacement for field type checkboxes.

**Comment by dgrammatiko** [comment]
@schnuti there will be a custom element for that. This also looks good, great work. Thanks

**Review by dgrammatiko — APPROVED** [review]

**Comment by laoneo** [comment]
I like the flip functionality, but for me it is confusing to have the check boxes connected to the degrees. Should we not just add two new buttons to flip the image horizontally and vertically?

**Comment by schnuti** [comment]
I have a solution where events are added to the checkboxes. The function is the same but as you don't have to click on or change the angel it might be less confusing.
What do you say about the non existing correlation between entered angle and the "quick" buttons. As i understand, it's a bit tricky and the code would run for each and every click on the arrows in the number field. A "softer" way is to use the same css for active and not active buttons. The active state is only used when you click on a button anyway. The valid angel comes from the number field.

**Comment by laoneo** [comment]
I would disconnect the flip actions from the angle. If you click on flip horizontally it flips it. That's all.

**Comment by schnuti** [comment]
That's not all. The logic has to be changed. As is, each iteration , both rotate and flip, starts with the image loaded at init. To keep this, the flip functionality must then get it's own plugin and that's overkill.

**Comment by laoneo** [comment]
I fear that how it is now, nobody will understand it. Just checked gimp and there you don't have to set a flag and then rotate it. Perhaps it makes code wise sense how it is now, but from user perspective it is not clear.

**Comment by laoneo** [comment]
I mean codewise, nothing should stop you to add a new listener and do the canvas stuff there.

**Comment by laoneo** [comment]
Where do we stay here?

**Comment by laoneo** [comment]
@schnuti any plans to proceed with this pr?

**Comment by laoneo** [comment]
@schnuti any plans to proceed with this pr?

**Comment by kasvith** [comment]
@schnuti have plans to move with pr ?

**Comment by schnuti** [comment]
As you do not accept it as is. No change awaiting. Use the idea if you like.

**Pull request closed without merging**
